version: '3'
services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
              - UID=${UID:-1000}
              - GID=${GID:-1000}
        image: mixpost
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'    
        depends_on:
            - mysql
            - redis
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'mixpost-mysql:/var/lib/mysql'
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s
    redis:
        image: 'redis:latest'
        command: redis-server --appendonly yes --replica-read-only no --requirepass "${REDIS_PASSWORD}"
        ports:
          - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
          - 'mixpost-redis:/data'
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          retries: 3
          timeout: 5s
volumes:
    mixpost-mysql:
        driver: local
    mixpost-redis:
        driver: local
    mixpost-storage:
        driver: local
    mixpost-logs:
        driver: local